// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace Cardiovascular_Disease_DetectionML.Model
{
    public class ModelInput
    {
        [ColumnName("id"), LoadColumn(0)]
        public float Id { get; set; }


        [ColumnName("age"), LoadColumn(1)]
        public float Age { get; set; }


        [ColumnName("gender"), LoadColumn(2)]
        public float Gender { get; set; }


        [ColumnName("height"), LoadColumn(3)]
        public float Height { get; set; }


        [ColumnName("weight"), LoadColumn(4)]
        public float Weight { get; set; }


        [ColumnName("ap_hi"), LoadColumn(5)]
        public float Ap_hi { get; set; }


        [ColumnName("ap_lo"), LoadColumn(6)]
        public float Ap_lo { get; set; }


        [ColumnName("cholesterol"), LoadColumn(7)]
        public float Cholesterol { get; set; }


        [ColumnName("gluc"), LoadColumn(8)]
        public float Gluc { get; set; }


        [ColumnName("smoke"), LoadColumn(9)]
        public float Smoke { get; set; }


        [ColumnName("alco"), LoadColumn(10)]
        public float Alco { get; set; }


        [ColumnName("active"), LoadColumn(11)]
        public float Active { get; set; }


        [ColumnName("cardio"), LoadColumn(12)]
        public bool Cardio { get; set; }


    }
}
